languaga: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/

install:
  - docker-compose -f pixgram-deployment/docker/docker-compose-build.yaml build --parallel
