apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
  selector:
    service: backend-user
