apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
  selector:
    service: reverseproxy
