version: '3'

services:
  reverseproxy:
    build:
      context: .
    image: ecoden/reverseproxy

  backend_user:
    build:
      context: ../../pixgram-restapi-user
    image: ecoden/pixgram-restapi-user

  backend_feed:
    build:
      context: ../../pixgram-restapi-feed
    image: ecoden/pixgram-restapi-feed

  frontend:
    build:
      context: ../../pixgram-client
    image: ecoden/pixgram-frontend:local
